[project]
name = "offnine"
description = "offnine"
readme = "README.md"
requires-python = ">=3.12"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = []
plugin_dirs = ["offnine/plugins"]
builtin_plugins = []
